# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pmg_ll_eigen <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nind_c, k_c, beta_c, sigma_c) {
    .Call(`_scRoPE_pmg_ll_eigen`, X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nind_c, k_c, beta_c, sigma_c)
}

pmg_der_eigen <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c) {
    .Call(`_scRoPE_pmg_der_eigen`, X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c)
}

pmg_hes_eigen <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c) {
    .Call(`_scRoPE_pmg_hes_eigen`, X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c)
}

ptmg_ll_eigen <- function(X_c, offset_c, Y_c, fam_c, fid_c, cumsumy_c, posind_c, posindy_c, nind_c, k_c, beta_c, sigma_c) {
    .Call(`_scRoPE_ptmg_ll_eigen`, X_c, offset_c, Y_c, fam_c, fid_c, cumsumy_c, posind_c, posindy_c, nind_c, k_c, beta_c, sigma_c)
}

ptmg_der_eigen <- function(X_c, offset_c, Y_c, fam_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c) {
    .Call(`_scRoPE_ptmg_der_eigen`, X_c, offset_c, Y_c, fam_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c)
}

call_cumsumy <- function(count, fid, k, ng) {
    .Call(`_scRoPE_call_cumsumy`, count, fid, k, ng)
}

call_posindy <- function(count, k, nc) {
    .Call(`_scRoPE_call_posindy`, count, k, nc)
}

center_m <- function(X_c) {
    .Call(`_scRoPE_center_m`, X_c)
}

cv_offset <- function(offset_c, input, nc) {
    .Call(`_scRoPE_cv_offset`, offset_c, input, nc)
}

get_cv <- function(offset_c, X_c, beta_c, cell_ind, ncell, nc) {
    .Call(`_scRoPE_get_cv`, offset_c, X_c, beta_c, cell_ind, ncell, nc)
}

get_cell <- function(X_c, fid_c, nb_c, k_c) {
    .Call(`_scRoPE_get_cell`, X_c, fid_c, nb_c, k_c)
}

ptmg_ll_der_eigen <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c) {
    .Call(`_scRoPE_ptmg_ll_der_eigen`, X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c)
}

ptmg_ll_der_hes_eigen <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c) {
    .Call(`_scRoPE_ptmg_ll_der_hes_eigen`, X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c)
}

opt_pml_hl <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c, reml, eps, ord) {
    .Call(`_scRoPE_opt_pml_hl`, X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c, reml, eps, ord)
}

opt_pml <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c, reml, eps, ord) {
    .Call(`_scRoPE_opt_pml`, X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c, reml, eps, ord)
}

opt_pml_constrained <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, beta_anchor, K_c, gamma_init, sigma_c, reml, eps, ord) {
    .Call(`_scRoPE_opt_pml_constrained`, X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, beta_anchor, K_c, gamma_init, sigma_c, reml, eps, ord)
}

opt_pml_nbm <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c, reml, eps, ord) {
    .Call(`_scRoPE_opt_pml_nbm`, X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c, reml, eps, ord)
}

pml_ll_der_eigen <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, logw_c, sigma_c) {
    .Call(`_scRoPE_pml_ll_der_eigen`, X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, logw_c, sigma_c)
}

ptmg_ll_der_hes_eigen_per_subject <- function(X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c) {
    .Call(`_scRoPE_ptmg_ll_der_hes_eigen_per_subject`, X_c, offset_c, Y_c, fid_c, cumsumy_c, posind_c, posindy_c, nb_c, nind_c, k_c, beta_c, sigma_c)
}

